server:
  port: 0

spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: movieService
  # PostgreSql Properties
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:30110/cine_vision
    password: '12345'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    defer-datasource-initialization: 'true'
  sql:
    init:
      mode: always
  # Apache Kafka Producer Properties
  kafka:
    producer:
      bootstrap-servers: localhost:30092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.kubeworks.movieService.entity.dto.EmailMessageKafkaDto
    topic:
      name: email_topics
  # Zipkin Properties
  zipkin:
    base-url: http://localhost:32000
  # Sleuth Properties
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: localhost
    port: 30210
    username: user
    password: test
    listener:
      direct:
        acknowledge-mode: manual
# Eureka Properties
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

# Circuit Breaker Properties
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  server:
    port: 8000
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 5s

mybatis:
  mapper-locations: classpath:mapper/*.xml

amqp:
  bindings:
    -
      exchange: comment.events
      routingKey: comment.created
      queue: comment.created.user-service
    -
      exchange: comment.events
      routingKey: comment.failed
      queue: comment.failed.user-service

  queues:
    user_created: user.created.comment-service
    comment_created: comment.created.user-service
    comment_failed: comment.failed.user-service

  routingKey:
    comment_created: comment.created
    comment_failed: comment.failed

  exchange:
    comment_events: comment.events

logging:
  level:
    root: DEBUG